name: AbangBakso
options:
  bundleIdPrefix: com.liauli.AbangBakso
  postGenCommand: pod install
targets:
  AbangBakso:
    type: application
    platform: iOS
    deploymentTarget: "17.2"
    scheme:
      testTargets:
        - AbangBaksoTests
    sources: 
      - AbangBakso
      - ./Fonts
    settings: 
      ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: YES
      ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    info:
      path: Info.plist
      properties:
        UILaunchScreen: []
        UIAppFonts: [TelkomselBatikSans-Regular.ttf, Poppins-Regular.ttf, TelkomselBatikSans-Bold.ttf]
    preBuildScripts:
      - script: |
                ./Pods/SwiftyMocky/bin/swiftymocky generate
                ./Pods/SwiftyMocky/bin/swiftymocky autoimport
        name: Generate Mocks
        outputFiles:
          - $(SRCROOT)/SampleTests/Mock.generated.swift
    postBuildScripts:
      - script: "\"${PODS_ROOT}/FirebaseCrashlytics/run\""
        name: Firebase
  AbangBaksoTests:
    type: bundle.unit-test
    info:
      path: Info.plist
    platform: iOS
    scheme:
      testTargets:
        - AbangBaksoTests
    deploymentTarget: "17.2"
    sources: [AbangBaksoTests]
    dependencies:
      - target: AbangBakso
  AbangBaksoUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.2"
    sources: [AbangBaksoUITests]
    info:
      path: Info.plist
    dependencies:
      - target: AbangBakso
    
