name: AbangBakso
options:
  bundleIdPrefix: com.liauli.AbangBakso
  postGenCommand: pod install
targets:
  AbangBakso:
    type: application
    platform: iOS
    deploymentTarget: "17.2"
    sources: [AbangBakso]
    info:
      path: Info.plist
    preBuildScripts:
      - script: |
                ./Pods/SwiftyMocky/bin/swiftymocky generate
                ./Pods/SwiftyMocky/bin/swiftymocky autoimport
        name: Generate Mocks
        outputFiles:
          - $(SRCROOT)/SampleTests/Mock.generated.swift
      - script: ${PODS_ROOT}/FirebaseCrashlytics/run
        name: Firebase
  AbangBaksoTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.2"
    sources: [AbangBaksoTests]
  AbangBaksoUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.2"
    sources: [AbangBaksoUITests]
    
