name: danger

on: [pull_request]

jobs:
  run danger:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Install Danger
        run: brew install danger/tap/danger-swift
      - name: run danger
        run: danger-swift pr
