name: run-tests

on: [push]

jobs:
  
  setup:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' 
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Install XcodeGen
        run: brew install xcodegen
      - name: Run Fastlane tests
        run: bundle exec fastlane gym
      - name: Cache Build
        id: cache-build
        uses: actions/cache/save@v3
        with:
          path: ./
          key: ${{ github.sha }}-setup

  test:
    needs: setup  
    runs-on: macos-latest
    steps:
      - uses: actions/cache/restore@v3
        id: restore-build
        with:
          path: ./
          key: ${{ github.sha }}-setup
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' 
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run Fastlane tests
        run: bundle exec fastlane unit_tests

  gym:
    needs: setup  
    runs-on: macos-latest
    steps:
      - uses: actions/cache/restore@v3
        id: restore-build
        with:
          path: ./
          key: ${{ github.sha }}-setup
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' 
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run Fastlane tests
        run: bundle exec fastlane gym

  secret_scan:
     runs-on: macos-latest
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v2
       - name: Install git-secrets
         run: brew install git-secrets
       - name: Run Secret Scan
         run: git secrets --scan
