name: SwiftLint PR Check

on:
  pull_request:
    paths:
      - '**/*.swift'  # Trigger only on changes to Swift files

jobs:
  swiftlint:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install SwiftLint
      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Lint
        run: |
          set -o pipefail
          swiftlint lint --strict --quiet | sed -E 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 title=Lint error,file=\1,line=\2,col=\3::\5\n\1:\2:\3/'