name: SwiftLint PR Check

on:
  pull_request:
    paths:
      - '**/*.swift'  # Trigger only on changes to Swift files

jobs:
  swiftlint:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install SwiftLint
      - name: Install SwiftLint
        run: brew install swiftlint

      # Step 3: Run SwiftLint on modified files and capture output
      - name: Run SwiftLint on modified files
        id: swiftlint
        run: |
          # Find modified Swift files and lint each one
          LINT_RESULT=$(git diff --name-only | grep "\.swift$" | while read filename; do
              swiftlint lint --path "$filename"
          done)
          
          echo "$LINT_RESULT"
          echo "lint_result=$LINT_RESULT" >> $GITHUB_ENV

      # Step 4: Post SwiftLint results as a PR comment
      - name: Post SwiftLint results to PR
        if: ${{ env.lint_result != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINT_RESULT: ${{ env.lint_result }}
        run: |
          # Prepare the comment body
          COMMENT_BODY="**SwiftLint Results** for PR #${{ github.event.pull_request.number }}:\n\n\`\`\`\n$LINT_RESULT\n\`\`\`"

          # Post the comment to the PR
          curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\": \"$COMMENT_BODY\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"